export const blobAssetMap = {
  'Line139.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/Line139-m13IgJkTAbco9x5Y6e6O8GoJFOY9al.svg',
  'Line140.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/Line140-FcNqEFfkF2M3eDXYteTUfX5gZlfi9R.svg',
  'Vector-1.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/Vector-1-daZbEB9EVYcRR0FpMFNwGTfWTuKYgp.svg',
  'Vector-2.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/Vector-2-jDNJC9ukj5qIjnSK9dMWsgKc4SxSCm.svg',
  'Vector-3.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/Vector-3-YSZKDiIJ8i3L2tngwcmEEbVHlFoySh.svg',
  'Vector.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/Vector-kXAPfTnX10E8YLcC85OVtKQUrfnB8C.svg',
  'hoituidiroituitraloicho.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/hoituidiroituitraloicho-JOX2VpwG9obVyq6wG01Okx4KLAIp5g.svg',
  'tieng-lua.mp3': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/tieng-lua-bfANrpcSLtbhSJJ42HsHnWOQbjJoUh.mp3',
  'tieng-mua.mp3': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/tieng-mua-kicnrQdwla5DlqJFBBIYzAv4L8w6eO.mp3',
  'tieng-song.mp3': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/tieng-song-N8Hbd9zsQyzKe6sU94PMc06sz9QmnY.mp3',
  'thong-diep/line.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/line-YXyoSlbJi1cCtj2zEqlY26O5E5MUrj.svg',
  'thong-diep/linexanh.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/linexanh-kc3opzK6IOeuSuoct1QIC6oT8NMzek.svg',
  'thong-diep/lathu.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/lathu-1XNF6kMnM0XFQyZwHVHeWJmGgr24ai.svg',
  'thong-diep/hop.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/hop-fnaSUepb5e5FuxQSQKxXX4W6SE7zIl.svg',
  'thong-diep/mastcot1.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/mastcot1-5MVSRSU1U3g7CL5qS6fLTqldCXyYLw.svg',
  'thong-diep/hau.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/hau-5lcPd64RAwNDP9M0Fy12GAHaCsLxTu.svg',
  'thong-diep/ma.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/ma-9qCtLApVNHmhxFn3R1ZoY06YXf8oLv.svg',
  'thong-diep/tot.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/tot-Llo24nUy7ZJttj2bb9xsVeD9870Qzb.svg',
  'thong-diep/tuong.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/tuong-blURPz5ytNHbXuDZI4kjBnGo5ndx6P.svg',
  'thong-diep/vua.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/vua-IyqN6GbnVjAzeA0zMgKPs72KlK49TS.svg',
  'thong-diep/xe.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/xe-HcGB2eXO8v1qJtkxKi1vQkyWDwQNmT.svg',
  'thong-diep/thu1.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/thu1-9GZeN55mRAZKtP31W3OGFlsSDMk83T.svg',
  'thong-diep/thu2.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/thu2-FBw3LupHf3Fc2T6PTXPPWNGyLwTtbv.svg',
  'thong-diep/thu3.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/thu3-4zKvzOrIVPhmu5lmRIUb3Opb3qfv05.svg',
  'thong-diep/thu4.svg': 'https://dccpjtvtpue8ic8d.public.blob.vercel-storage.com/assets/thong-diep/thu4-6ENS095e0XZDNU0VOUxS3jfLK9AFZj.svg',
}
