export const selfHelpBooks = [
  {
    id: 'atomic-habits',
    title: 'Atomic Habits',
    author: 'James Clear',
    tag: 'Habits',
    coverClass: 'book-cover-habits',
    pdfUrl: '',
    note: 'Một cuốn dễ bắt đầu nếu bạn muốn thay đổi từ những hành động nhỏ. Sách xoay quanh việc thiết kế hệ thống, môi trường và thói quen 1% mỗi ngày.',
    takeaway: 'Phù hợp khi bạn muốn xây routine học tập, làm việc, tập luyện hoặc bỏ một thói quen xấu.',
  },
  {
    id: 'the-power-of-now',
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    tag: 'Mindfulness',
    coverClass: 'book-cover-now',
    pdfUrl: '',
    note: 'Một cuốn chậm và tĩnh hơn, tập trung vào việc quay về hiện tại thay vì bị kéo đi bởi suy nghĩ cũ hoặc lo lắng tương lai.',
    takeaway: 'Phù hợp cho những ngày đầu óc quá ồn, cần một cách đọc nhẹ để thở lại.',
  },
  {
    id: 'the-gifts-of-imperfection',
    title: 'The Gifts of Imperfection',
    author: 'Brene Brown',
    tag: 'Self-worth',
    coverClass: 'book-cover-worth',
    pdfUrl: '',
    note: 'Cuốn sách nói về việc bớt sống theo kỳ vọng hoàn hảo, học cách chấp nhận bản thân và xây sự can đảm từ những điều rất đời thường.',
    takeaway: 'Phù hợp khi bạn đang muốn dịu với chính mình hơn, nhất là lúc tự so sánh hoặc tự trách.',
  },
  {
    id: 'mans-search-for-meaning',
    title: "Man's Search for Meaning",
    author: 'Viktor E. Frankl',
    tag: 'Meaning',
    coverClass: 'book-cover-meaning',
    pdfUrl: '',
    note: 'Một cuốn sâu và nặng hơn, nhưng rất đáng đọc. Frankl viết về ý nghĩa sống, khả năng lựa chọn thái độ, và cách con người đi qua nghịch cảnh.',
    takeaway: 'Phù hợp khi bạn cần một góc nhìn lớn hơn về mục đích, chịu đựng và hy vọng.',
  },
  {
    id: 'deep-work',
    title: 'Deep Work',
    author: 'Cal Newport',
    tag: 'Focus',
    coverClass: 'book-cover-habits',
    pdfUrl: '',
    note: 'Cuốn sách nói về khả năng tập trung sâu trong một thế giới đầy phân tâm. Nó hợp với những ai muốn làm việc chất lượng hơn thay vì chỉ bận rộn hơn.',
    takeaway: 'Phù hợp khi bạn cần xây thói quen học, làm project hoặc sáng tạo mà không bị điện thoại kéo đi liên tục.',
  },
  {
    id: 'mindset',
    title: 'Mindset',
    author: 'Carol S. Dweck',
    tag: 'Growth',
    coverClass: 'book-cover-now',
    pdfUrl: '',
    note: 'Cuốn sách xoay quanh tư duy phát triển: khả năng học, sai, thử lại và tiến bộ qua quá trình thay vì đóng khung bản thân bằng kết quả.',
    takeaway: 'Phù hợp khi bạn dễ nản vì thất bại, điểm số, feedback hoặc cảm giác mình không đủ giỏi.',
  },
  {
    id: 'the-mountain-is-you',
    title: 'The Mountain Is You',
    author: 'Brianna Wiest',
    tag: 'Healing',
    coverClass: 'book-cover-worth',
    pdfUrl: '',
    note: 'Một cuốn về self-sabotage và những mô thức khiến mình tự cản đường chính mình. Giọng sách thiên về chữa lành và tự quan sát.',
    takeaway: 'Phù hợp khi bạn biết mình muốn thay đổi nhưng vẫn cứ mắc lại ở cùng một vòng lặp.',
  },
  {
    id: 'the-subtle-art',
    title: 'The Subtle Art of Not Giving a F*ck',
    author: 'Mark Manson',
    tag: 'Values',
    coverClass: 'book-cover-meaning',
    pdfUrl: '',
    note: 'Cuốn sách nói thẳng về việc chọn điều đáng quan tâm, bớt chạy theo kỳ vọng ngoài kia và sống theo giá trị thật sự của mình.',
    takeaway: 'Phù hợp khi bạn đang quá tải vì muốn làm vừa lòng quá nhiều người hoặc quá nhiều mục tiêu.',
  },
  {
    id: 'cant-hurt-me',
    title: "Can't Hurt Me",
    author: 'David Goggins',
    tag: 'Discipline',
    coverClass: 'book-cover-habits',
    pdfUrl: '',
    note: 'Một cuốn rất mạnh về kỷ luật, sức bền tinh thần và việc vượt qua giới hạn bản thân. Tone sách quyết liệt hơn các cuốn dịu nhẹ.',
    takeaway: 'Phù hợp khi bạn cần một cú hích năng lượng, nhất là lúc muốn rèn sự bền bỉ và cam kết.',
  },
  {
    id: 'the-untethered-soul',
    title: 'The Untethered Soul',
    author: 'Michael A. Singer',
    tag: 'Awareness',
    coverClass: 'book-cover-now',
    pdfUrl: '',
    note: 'Cuốn sách mời bạn quan sát dòng suy nghĩ và cảm xúc thay vì bị cuốn theo chúng. Nó nhẹ, thiền tính và hợp để đọc chậm.',
    takeaway: 'Phù hợp khi bạn muốn hiểu tâm trí mình hơn và học cách tạo khoảng cách với những suy nghĩ nặng nề.',
  },
  {
    id: 'daring-greatly',
    title: 'Daring Greatly',
    author: 'Brene Brown',
    tag: 'Courage',
    coverClass: 'book-cover-worth',
    pdfUrl: '',
    note: 'Một cuốn về sự dễ tổn thương, lòng can đảm và việc xuất hiện thật hơn trong các mối quan hệ, công việc và cuộc sống.',
    takeaway: 'Phù hợp khi bạn sợ bị đánh giá, sợ không đủ tốt, nhưng vẫn muốn sống thật và kết nối sâu hơn.',
  },
  {
    id: 'essentialism',
    title: 'Essentialism',
    author: 'Greg McKeown',
    tag: 'Clarity',
    coverClass: 'book-cover-meaning',
    pdfUrl: '',
    note: 'Cuốn sách giúp bạn phân biệt điều thật sự quan trọng với những việc chỉ làm mình bận rộn. Trọng tâm là chọn ít hơn nhưng đúng hơn.',
    takeaway: 'Phù hợp khi lịch của bạn quá đầy, việc gì cũng thấy cần, nhưng cuối ngày vẫn không thấy mình đi đúng hướng.',
  },
  {
    id: 'make-your-bed',
    title: 'Make Your Bed',
    author: 'William H. McRaven',
    tag: 'Discipline',
    coverClass: 'book-cover-habits',
    pdfUrl: '',
    note: 'Một cuốn ngắn, dễ đọc, bắt đầu từ những hành động nhỏ nhưng có thể tạo cảm giác trật tự và chủ động cho một ngày.',
    takeaway: 'Phù hợp khi bạn muốn một cuốn đọc nhanh để lấy lại nhịp sống và kỷ luật cơ bản.',
  },
  {
    id: 'ikigai',
    title: 'Ikigai',
    author: 'Hector Garcia',
    tag: 'Purpose',
    coverClass: 'book-cover-now',
    pdfUrl: '',
    note: 'Cuốn sách nói về lối sống có mục đích, sự giản dị và những thói quen giúp con người sống lâu, sống chậm và sống có ý nghĩa hơn.',
    takeaway: 'Phù hợp khi bạn muốn nghĩ về niềm vui sống, công việc, sức khỏe và nhịp sống bền vững.',
  },
  {
    id: 'the-four-agreements',
    title: 'The Four Agreements',
    author: 'Don Miguel Ruiz',
    tag: 'Wisdom',
    coverClass: 'book-cover-meaning',
    pdfUrl: '',
    note: 'Một cuốn nhỏ về bốn nguyên tắc sống giúp mình bớt mắc kẹt trong lời nói, kỳ vọng và phán xét.',
    takeaway: 'Phù hợp khi bạn muốn một bộ nguyên tắc gọn để nhìn lại cách mình giao tiếp và phản ứng.',
  },
  {
    id: 'tiny-habits',
    title: 'Tiny Habits',
    author: 'BJ Fogg',
    tag: 'Habits',
    coverClass: 'book-cover-habits',
    pdfUrl: '',
    note: 'Cuốn sách tập trung vào cách thiết kế hành vi thật nhỏ để dễ bắt đầu và dễ duy trì, thay vì trông chờ vào động lực.',
    takeaway: 'Phù hợp khi bạn từng đặt mục tiêu lớn rồi bỏ cuộc vì nó quá nặng để bắt đầu.',
  },
  {
    id: 'think-again',
    title: 'Think Again',
    author: 'Adam Grant',
    tag: 'Learning',
    coverClass: 'book-cover-now',
    pdfUrl: '',
    note: 'Một cuốn về khả năng suy nghĩ lại, đổi góc nhìn và học cách không bám chặt vào điều mình từng tin là đúng.',
    takeaway: 'Phù hợp khi bạn muốn linh hoạt hơn trong học tập, tranh luận, công việc và các mối quan hệ.',
  },
  {
    id: 'the-alchemist',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    tag: 'Dreams',
    coverClass: 'book-cover-worth',
    pdfUrl: '',
    note: 'Một câu chuyện ngụ ngôn nhẹ nhàng về hành trình theo đuổi ước mơ, lắng nghe trực giác và tin vào dấu hiệu trên đường đi.',
    takeaway: 'Phù hợp khi bạn muốn đọc một cuốn giàu cảm hứng nhưng không quá nặng lý thuyết.',
  },
  {
    id: 'show-your-work',
    title: 'Show Your Work',
    author: 'Austin Kleon',
    tag: 'Creative',
    coverClass: 'book-cover-meaning',
    pdfUrl: '',
    note: 'Cuốn sách khuyến khích chia sẻ quá trình làm việc, học cách xuất hiện và để người khác nhìn thấy hành trình sáng tạo của mình.',
    takeaway: 'Phù hợp khi bạn muốn xây portfolio, đăng sản phẩm, hoặc bớt sợ việc đưa tác phẩm ra ngoài.',
  },
  {
    id: 'steal-like-an-artist',
    title: 'Steal Like an Artist',
    author: 'Austin Kleon',
    tag: 'Creative',
    coverClass: 'book-cover-habits',
    pdfUrl: '',
    note: 'Một cuốn ngắn về cách học từ nguồn cảm hứng, remix ý tưởng và bắt đầu sáng tạo từ những thứ mình yêu thích.',
    takeaway: 'Phù hợp khi bạn đang bí ý tưởng hoặc nghĩ mình phải hoàn toàn độc đáo mới được bắt đầu.',
  },
  {
    id: 'the-war-of-art',
    title: 'The War of Art',
    author: 'Steven Pressfield',
    tag: 'Resistance',
    coverClass: 'book-cover-worth',
    pdfUrl: '',
    note: 'Cuốn sách gọi tên sự trì hoãn và lực cản bên trong mỗi khi mình muốn làm điều quan trọng.',
    takeaway: 'Phù hợp khi bạn cứ trì hoãn viết, học, tập, làm dự án hoặc bắt đầu thứ mình thật sự quan tâm.',
  },
  {
    id: 'start-with-why',
    title: 'Start With Why',
    author: 'Simon Sinek',
    tag: 'Purpose',
    coverClass: 'book-cover-now',
    pdfUrl: '',
    note: 'Một cuốn về việc tìm lý do cốt lõi phía sau hành động, thương hiệu hoặc lựa chọn nghề nghiệp.',
    takeaway: 'Phù hợp khi bạn muốn hiểu rõ hơn vì sao mình làm điều mình đang làm.',
  },
  {
    id: 'grit',
    title: 'Grit',
    author: 'Angela Duckworth',
    tag: 'Growth',
    coverClass: 'book-cover-habits',
    pdfUrl: '',
    note: 'Cuốn sách nói về đam mê, sự bền bỉ và khả năng theo đuổi mục tiêu dài hạn qua nhiều lần va vấp.',
    takeaway: 'Phù hợp khi bạn cần niềm tin rằng tiến bộ dài hạn đến từ sự bền bỉ chứ không chỉ tài năng.',
  },
  {
    id: 'the-5-am-club',
    title: 'The 5 AM Club',
    author: 'Robin Sharma',
    tag: 'Routine',
    coverClass: 'book-cover-meaning',
    pdfUrl: '',
    note: 'Một cuốn pha storytelling về routine buổi sáng, năng lượng cá nhân và cách bắt đầu ngày mới có chủ đích.',
    takeaway: 'Phù hợp khi bạn muốn thử thiết kế lại buổi sáng để học, tập luyện hoặc làm việc sâu hơn.',
  },
]
